packages:
  - apps/*
  - packages/*

catalog:
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  '@phaicom/eslint-config': ^0.11.1
  '@tailwindcss/vite': ^4.1.18
  astro: ^5.16.16
  eslint: ^9.39.2
  eslint-plugin-better-tailwindcss: ^4.0.2
  eslint-plugin-format: ^1.3.1
  lint-staged: ^16.2.7
  nuxt: ^4.3.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.18
  turbo: ^2.8.0
  typescript: ^5.9.3
  vue: ^3.5.27
  vue-router: ^4.6.4

catalogMode: prefer

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

shamefullyHoist: true
