/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as publicIndexRouteImport } from "./routes/(public)/index";
import { Route as publicRouteRouteImport } from "./routes/(public)/route";
import { Route as rootRouteImport } from "./routes/__root";

const publicRouteRoute = publicRouteRouteImport.update({
  id: "/(public)",
  getParentRoute: () => rootRouteImport,
} as any);
const publicIndexRoute = publicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof publicIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof publicIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(public)": typeof publicRouteRouteWithChildren;
  "/(public)/": typeof publicIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/(public)" | "/(public)/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(public)": {
      id: "/(public)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof publicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/": {
      id: "/(public)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof publicRouteRoute;
    };
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute;
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
};

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(publicRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
